
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np
arry1D =  np.array([range(0,10)])
print(arry1D)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [2]:
import numpy as np

arry3 = np.array([[[1,3,4],
                   [1,2,3],
                   [6,5,4]
                   ]])
arry3

array([[[1, 3, 4],
        [1, 2, 3],
        [6, 5, 4]]])

Access the element at the second row, second column.


In [18]:
arry3[0][1][1]

2

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [20]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
def operation():
    add = array1 + array2
    print(f"Addition {add}") 
    sub = array1 - array2
    print(f"substraction {sub}")
    multiply = array1 * array2
    print(f"Multiplication {multiply}") 
    division = array1 / array2
    print(f"Division {division}") 

operation()

Addition [5 7 9]
substraction [-3 -3 -3]
Multiplication [ 4 10 18]
Division [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [22]:
import numpy as np
ary = np.array([1,2,3,4,5])

sum_ARY = np.sum(ary)

mean = np.mean(ary)

standerd_ary = np.std(ary)

print("Sum of arrray",sum_ARY)
print("Mean of arrray",mean)
print("Standard deviation of arrray", standerd_ary)


Sum of arrray 15
Mean of arrray 3.0
Standard deviation of arrray 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [24]:
array2x3 = [1,2,3,4,5,6]

reshape_of_array = np.reshape(array2x3 , (2,3))

print(reshape_of_array)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [26]:
array5x5 = np.array([[1,2,3,4,5],
                     [2,4,6,8,10],
                     [1,3,5,7,9],
                     [4,3,2,1,1],
                     [3,2,14,5,6],
                     ])
array5x5

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9],
       [ 4,  3,  2,  1,  1],
       [ 3,  2, 14,  5,  6]])

Replace all values in the sub-array with a specific value.


In [30]:
import numpy as np
replace_value = array5x5.T
print(f'previous array \n {array5x5} \n and Replace Array \n {replace_value}')

previous array 
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [ 4  3  2  1  1]
 [ 3  2 14  5  6]] 
 and Replace Array 
 [[ 1  2  1  4  3]
 [ 2  4  3  3  2]
 [ 3  6  5  2 14]
 [ 4  8  7  1  5]
 [ 5 10  9  1  6]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [ ]:
import numpy as np

array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

subarray = array[1:3]

print(subarray)


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [31]:
import numpy as np
array2D = np.array([[0,1,2],
                    [0,1,2],
                    [0,1,2]
                    ])
array2D

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [32]:
array1D = [1,2,3]

broadcast = array2D + array1D

print(broadcast)

[[1 3 5]
 [1 3 5]
 [1 3 5]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [39]:
import numpy as np

array1 = np.array([[1,2,3],
                   [0,7,9]
                   ])
array2 = np.array([[0,4,9],
                   [1,6,8]
                   ])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

concatenat_horztl = np.concatenate((array1, array2), axis=1)


concatenat_vertl = np.concatenate((array1, array2), axis=0)

print("\nConcatenated horizontally:")
print(concatenat_horztl)
print("\nConcatenated vertically:")
print(concatenat_vertl)



Array 1:
[[1 2 3]
 [0 7 9]]

Array 2:
[[0 4 9]
 [1 6 8]]

Concatenated horizontally:
[[1 2 3 0 4 9]
 [0 7 9 1 6 8]]

Concatenated vertically:
[[1 2 3]
 [0 7 9]
 [0 4 9]
 [1 6 8]]


In [40]:
# Split concatenated array horizontally
split_horzontl = np.split(concatenat_horztl, 2, axis=1)
array1_h, array2_h = split_horzontl

# Split concatenated array vertically
split_vertl = np.split(concatenat_vertl, 2, axis=0)
array1_v, array2_v = split_vertl

print("\nArray 1 after splitting (horizontal):")
print(array1_h)
print("\nArray 2 after splitting (horizontal):")
print(array2_h)

print("\nArray 1 after splitting (vertical):")
print(array1_v)
print("\nArray 2 after splitting (vertical):")
print(array2_v)


Array 1 after splitting (horizontal):
[[1 2 3]
 [0 7 9]]

Array 2 after splitting (horizontal):
[[0 4 9]
 [1 6 8]]

Array 1 after splitting (vertical):
[[1 2 3]
 [0 7 9]]

Array 2 after splitting (vertical):
[[0 4 9]
 [1 6 8]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

