In [1]:
import numpy as np
matrix = []
metrix = []
print("-------------------------------FOR VALUE A ---------------------------------")
print(" 1:[2 x 2] 2:[3 x 3] \n 3:[2 x 3] 4:[2 x 1] \n 5:[3 x 2] 6:[3 x 1] ")

size = int(input("-----Enter Size of a Matrix-----"))

if size == 1:
    row1 = list(map(int, input("Enter the elements of the first row separated by space: ").split()))
    matrix.append(row1)
    row2 = list(map(int, input("Enter the elements of the Second row separated by space: ").split()))
    matrix.append(row2)
    
elif size == 2:
    row1 = list(map(int, input("Enter the elements of the first row separated by space: ").split()))
    matrix.append(row1)
    row2 = list(map(int, input("Enter the elements of the Second row separated by space: ").split()))
    matrix.append(row2)
    row3 = list(map(int, input("Enter the elements of the Third row separated by space: ").split()))
    matrix.append(row3)
    
    

elif size == 3:
    row1 = list(map(int, input("Enter the elements of the first row separated by space: ").split()))
    matrix.append(row1)
    row2 = list(map(int, input("Enter the elements of the Second row separated by space: ").split()))
    matrix.append(row2)
    # Print the resulting matrix with the desired format
    

elif size == 4:
    row1 = list(map(int, input("Enter the elements of the first row separated by space: ").split()))
    matrix.append(row1)
    row2 = list(map(int, input("Enter the elements of the Second row separated by space: ").split()))
    matrix.append(row2)
    # Print the resulting matrix with the desired format
    

elif size == 5:
    row1 = list(map(int, input("Enter the elements of the first row separated by space: ").split()))
    matrix.append(row1)
    row2 = list(map(int, input("Enter the elements of the Second row separated by space: ").split()))
    matrix.append(row2)
    row3 = list(map(int, input("Enter the elements of the Third row separated by space: ").split()))
    matrix.append(row3)
    # Print the resulting matrix with the desired format
    

elif size == 6:
    row1 = list(map(int, input("Enter the elements of the first row separated by space: ").split()))
    matrix.append(row1)
    row2 = list(map(int, input("Enter the elements of the Second row separated by space: ").split()))
    matrix.append(row2)
    row3 = list(map(int, input("Enter the elements of the Third row separated by space: ").split()))
    matrix.append(row3)
    # Print the resulting matrix with the desired format
    


else:
    print("Enter Valid matrix")

print("-------------------------------FOR VALUE B ---------------------------------")

print("1:(2x1) , 2:(3x1)")
size2 = int(input("Enter size of Matrix for B "))
if size2 == 1:
    row1 = list(map(int, input("Enter the elements of the first row separated by space: ").split()))
    metrix.append(row1)
    row2 = list(map(int, input("Enter the elements of the Second row separated by space: ").split()))
    metrix.append(row2)
# Print the resulting matrix with the desired format
    

elif size2 == 2:
    row1 = list(map(int, input("Enter the elements of the first row :").split()))
    metrix.append(row1)
    row2 = list(map(int, input("Enter the elements of the Second row :").split()))
    metrix.append(row2)
    row3 = list(map(int, input("Enter the elements of the Second row :").split()))
    metrix.append(row3)
# Print the resulting matrix with the desired format
    

else:
    print("Please Enter Valid Matrix")

A = np.array(matrix)
B = np.array(metrix)

print(f"matrix A is :\n {A} and Matrix B is :\n {B}")
#Transposed Matrix A
At = A.T
print("transposed matrix :\n",At )

# Transposed Matrix multiply with matrix ----> A 
ATA = np.dot(At , A)
print(f"A^t.A =\n {ATA}")

# Transposed Matrix matrix Multiply with ----->B
ATB = np.dot(At , B)
print(f"A^t.B =\n {ATB}")

# Inverse of A^t.B
ATA_inv = np.linalg.inv(ATA)
print(f"Inverse of A^t.A = \n {ATA_inv}")

X = np.dot(ATA_inv, ATB)
print("------------answer----------------")
print("\n least square",X)





-------------------------------FOR VALUE A ---------------------------------
 1:[2 x 2] 2:[3 x 3] 
 3:[2 x 3] 4:[2 x 1] 
 5:[3 x 2] 6:[3 x 1] 


-----Enter Size of a Matrix----- 5
Enter the elements of the first row separated by space:  1  1
Enter the elements of the Second row separated by space:  0  1
Enter the elements of the Third row separated by space:  1  0


-------------------------------FOR VALUE B ---------------------------------
1:(2x1) , 2:(3x1)


Enter size of Matrix for B  2
Enter the elements of the first row : 1
Enter the elements of the Second row : 1
Enter the elements of the Second row : 0


matrix A is :
 [[1 1]
 [0 1]
 [1 0]] and Matrix B is :
 [[1]
 [1]
 [0]]
transposed matrix :
 [[1 0 1]
 [1 1 0]]
A^t.A =
 [[2 1]
 [1 2]]
A^t.B =
 [[1]
 [2]]
Inverse of A^t.A = 
 [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
------------answer----------------

 least square [[0.]
 [1.]]
